### ISSUE TITLE
[Feature request] Update Restic 0.14.0

### ISSUE THREAD

**Issue by ngosang** [lhns/restic-android#115]
Restic 0.14.0 includes several improvements and new features.
https://github.com/restic/restic/releases/tag/v0.14.0

The most important change is from version 0.14.0 they bumped the repository version to 2. Version 2 is the default and version 1 is still compatible but it doesn't support new features like compression.

That means this app is not working with repositories v2 (created with Restic .14.0)

Here is info about the migration to v2 => https://restic.readthedocs.io/en/stable/045_working_with_repos.html#upgrading-the-repository-format-version

**Comment by ngosang** [comment]
I think this could be related too https://github.com/ngosang/restic-exporter/issues/1

**Comment by lhns** [comment]
fixed in v0.4.1
