### ISSUE TITLE
wrong APK attached to release 0.3.0?

### ISSUE THREAD

**Issue by IzzySoft** [lhns/restic-android#135]
The APK attached to release 0.3.0 identifies as

    package: name='de.lolhens.resticui' versionCode='1941588398' versionName='0.2.2'

Could you please replace it by the correct one? Or is a new release already pending (0.3.0 was about a year ago)? Thanks in advance!

**Comment by lhns** [comment]
Weird. When I analyze the release asset from GitHub in IntelliJ it shows the correct version:
![image](https://user-images.githubusercontent.com/1524059/224168029-d2e8810d-e562-47b9-b238-3f61b2f7a660.png)

**Comment by IzzySoft** [comment]
That's absolutely strange. It even shows `versionCode: 9`. Let me dig in again **manually** this time:

```bash
wget https://github.com/lhns/restic-android/releases/download/0.3.0/app-release.apk
aapt d badging app-release.apk | head -n 1

package: name='de.lolhens.resticui' versionCode='9' versionName='0.3.0' platformBuildVersionName='11' platformBuildVersionCode='30' compileSdkVersion='30' compileSdkVersionCodename='11'
```

Right. So where the heck did it get that other APK from? ARGH! It's even worse!!! That's the APK from the 2.2 release:

```bash
wget https://github.com/lhns/restic-android/releases/download/0.2.2/app-release.apk
aapt d badging app-release.apk | head -n 1

package: name='de.lolhens.resticui' versionCode='1941588398' versionName='0.2.2' platformBuildVersionName='11' platformBuildVersionCode='30' compileSdkVersion='30' compileSdkVersionCodename='11'
```

You've set the `versionCode` to `1941588398` with that. You NEVER can decrease `versionCode`: for Android, higher `versionCode` means newer version. If there's a lower one after that, it will be rejected/ignored. Existing users of v0.2.2 cannot upgrade to your v0.3.0 without uninstalling and re-installing. Thus my updater was fetching the 0.3.0 APK each day for almost a year now, just to throw it away afterwards as a "newer" one was already present :scream: 

So how shall we continue from here? We have 2 options:

* you leave it as-is, forcing users to miss the update or, if they find it somehow, having to uninstall first (for that I could manually replace the APK in my repo), or
* you make a new release with a higher `versionCode` and keep going from there.

Which way do you prefer?

**Comment by lhns** [comment]
Thanks for the indepth analysis! I previously numbered the releases using some github-global run-id and had to change that to using the build number because at some point the value was over the allowed max of 2100000000. I offset that build number in 244c5ddc6ea755863957a75813db4d0c6cd51d98 so next release should fix the issue.

**Comment by lhns** [comment]
should be fixed in v0.4.1

**Comment by IzzySoft** [comment]
> Thanks for the indepth analysis!

Gladly done! And I'll forward your thanks to the user reporting it to me, thus triggering my analysis :smiley:

> I offset that build number in https://github.com/lhns/restic-android/commit/244c5ddc6ea755863957a75813db4d0c6cd51d98 so next release should fix the issue.

Cool!

> should be fixed in v0.4.1

Close, but no cigar: v0.2.2 has `1941588398`, v0.4.1 `1941588012` and thus is still smaller by 386. Needs one more kick it seems:

```gradle
versionCode getBuildNumber() + 1941588387
```
I should do it I guess?

**Comment by IzzySoft** [comment]
PS: I also noticed the size increase which now goes beyond the limits of my repo (which are 30 MB per app). Would it be possible to create per-ABI APKs? Maybe just have one with both armeabi+arm64 and a second with x86* would already help getting it inside the limits (I'd then pick the ARM one as it's compatible with most devices). Thanks in advance!

**Comment by IzzySoft** [comment]
> Oh no every workflow seems to be numbered individually...

Maybe simply use `UnixTime + 270000000`? With `1948476780` that would be "just beyond" what v2.2 had. And how likely is it that you have 2 different versions at the very same second?

> I will look into the per-ABI apk thing.

Wonderful, thanks!

**Comment by lhns** [comment]
The version code should be correct now and I published split abi apks.

**Comment by IzzySoft** [comment]
Thanks! That worked out excellently! 0.4.2 will show up [in my repo](https://apt.izzysoft.de/fdroid/index/apk/de.lolhens.resticui) with the next sync (around 7 pm UTC) then. Thanks to the per-ABI APKs, I can now keep 2 versions available (picking the armeabi one for widest compatibility and to support users achieving longevity with their older devices; with 32bit devices dying out, one day I'll of course switch over to arm64).

PS: If you wish I can provide you the metadata I've set up here via PR in [Fastlane format](https://gitlab.com/-/snippets/1895688), so you'd be in control of how your app is presented here (together with the Fastlane binaries, that could even be used to deploy to other places, like PlayStore). Just let me know if you want it.

**Comment by lhns** [comment]
Thanks for helping! The fastlane metadata would be very cool!

**Comment by IzzySoft** [comment]
> Thanks for helping!

Gladly!

> The fastlane metadata would be very cool!

On it. Expect the PR showing up in a few minutes. Note that I "de-framed" the screenshots you provide with your readme. Background is to make better use of the screen estate on smaller screens (consider people finding your app via their F-Droid client).
