### ISSUE TITLE
Binary blobs

### ISSUE THREAD

**Issue by robertgzr** [lhns/restic-android#166]
This repo contains binary *.so libraries of restic, proot, libtalloc [commited here](https://github.com/lhns/restic-android/tree/main/app/src/main/jniLibs)

how do you create these binary blobs? 

it looks like at least proot is licensed under GPL, which might cause some issues. i'm not a lawyer but i suspect you have to at least provide the source (or refer to it) your binary was built from :p

it's also not great since updating those binaries in the git tree will bloat the size of the checkout, since git keeps copies of the old revisions around.

**Comment by lhns** [comment]
Yes the process is not optimal but I haven't automated that part yet.
The sources of the blobs are described here: https://github.com/lhns/restic-android/discussions/145

**Comment by lhns** [comment]
fixed in 06e9efe138bb01da7923fe779b4dfb6a3668805f
